apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
    tier: platform
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        tier: platform
        environment: dev
    spec:
      containers:
      - name: jenkins
        image: jenkins
        ports:
        - containerPort: 8090
        - containerPort: 50000
        volumeMounts:
        - name: jenkins
          mountPath: /var/lib/jenkins
      volumes:
        - name: jenkins
          persistentVolumeClaim:
            claimName: jenkins-data
      securityContext:
        fsGroup: 1000