apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mogambo-blue
  namespace: test
  labels:
    tier: deployment
    release: blue
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  paused: false
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
      release: blue
    matchExpressions:
      - {key: version, operator: In, values: [v1,latest,v2]}
  template:
    metadata:
      name: mogambofrontend
      labels:
        app: frontend
        version: v1
        release: blue
    spec:
      containers:
        - name: mogambocontainer
          image: schoolofdevops/frontend:v1.0
        
        