apiVersion: v1
kind: Service
metadata:
  name: mogamboservice
  namespace: test
spec:
  selector:
    app: frontend
    release: green
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 31767
  type: NodePort
