apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginxVolume
          mountPath: /etc/nginx/
  volumes:
    - name: nginxVolume
      hostPath: 
        path: /etc/nginx/
        type: DirectoryOrCreate        