apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    role: role
spec:
  replicas: 3
  selector:
    app: robotshop
  template:
    metadata:
      name: robotshop
      labels:
        app: robotshop
    spec: 
      containers:
        - name: web
          image: robotshop/rs-web:latest
          ports:
            - containerPort: 8080
              protocol: TCP